ppw_story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('statuslist.urls', namespace='statuslist')),
]

statuslist/urls.py
from django.urls import path
from .views import *

app_name = 'statuslist'

urlpatterns = [
    path('', statuslist, name='statuslist'),
    path('add_status/',add_status, name='add_status'),
]

statuslist/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    waktu = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

statuslist/forms.py
from django import forms

class StatusForm(forms.Form):
    status = forms.CharField(max_length=300)

statuslist/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

# Create your views here.

def statuslist(request):
    form = StatusForm()
    status = Status.objects.all()
    context = {
        'form': form,
        'status': status
    }
    return render(request, 'index.html', context)


def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            new_status = Status.objects.create(status = request.POST['status'])
        return redirect('/')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Story 6</title>
</head>
<body>
  <div class="container">
    <h1>Halo, Apa Kabar?</h1>
    <form action="{% url 'statuslist:add_status'%}" method="post">
      <table>
        {%csrf_token%}
        {{form.as_table}}
      </table>
      <input type="submit" value="Submit">
    </form>
    <table>
      {% for status in status %}
      <tr>
        <td>
          {{status.status}}
        </td>
        <td>
          {{status.waktu}}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
</body>
</html>